package logo.lsp.lexer;

public enum TokenType {
    NUMBER,
    STRING,
    WORD,
    BOOLEAN,

    IDENTIFIER,

    VARIABLE,

    FORWARD, BACK, LEFT, RIGHT,
    PENUP, PENDOWN, PENCOLOR, SETPENCOLOR, SETPENSIZE,
    CLEAN, CLEARSCREEN, HOME,
    SETX, SETY, SETXY, SETPOS, SETSPEED,
    HIDETURTLE, SHOWTURTLE,
    FILL, LABEL,

    MAKE, LOCAL, THING,
    PRINT, SHOW, TYPE,
    IF, IFELSE, TEST, IFTRUE, IFFALSE,
    REPEAT, FOREVER, WHILE, UNTIL, FOR,
    TO, END,
    OUTPUT, STOP,
    RUN, APPLY,
    LIST, FIRST, LAST, BUTFIRST, BUTLAST, ITEM, COUNT,
    SENTENCE, FPUT, LPUT,
    AND, OR, NOT,

    SUM, DIFFERENCE, PRODUCT, QUOTIENT, REMAINDER, MODULO, POWER, SQRT, ABS, MINUS,

    EQUALP, NOTEQUALP, LESSP, GREATERP, LESSEQUALP, GREATEREQUALP, EQUAL_SIGN,

    LPAREN,
    RPAREN,
    LBRACKET,
    RBRACKET,
    COLON,          // before variable names
    PLUS,
    MINUS_OP,
    STAR,
    SLASH,
    LESS,
    GREATER,
    CARET,      // ^

    NEWLINE,
    EOF,
    UNKNOWN

}
